name: nexusEnv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - aiofiles==23.2.1
    - aiohappyeyeballs==2.5.0
    - aiohttp==3.11.13
    - aiosignal==1.3.2
    - annotated-types==0.7.0
    - anyio==4.8.0
    - asttokens==3.0.0
    - attrs==25.1.0
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - click==8.1.8
    - comm==0.2.2
    - dataclasses-json==0.6.7
    - debugpy==1.8.13
    - decorator==5.2.1
    - distro==1.9.0
    - et-xmlfile==2.0.0
    - executing==2.2.0
    - fastapi==0.115.11
    - ffmpy==0.5.0
    - filelock==3.17.0
    - frozenlist==1.5.0
    - fsspec==2025.3.0
    - gradio==5.20.1
    - gradio-client==1.7.2
    - greenlet==3.1.1
    - groovy==0.1.2
    - groq==0.18.0
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - httpx-sse==0.4.0
    - huggingface-hub==0.29.2
    - idna==3.10
    - ipykernel==6.29.5
    - ipython==9.0.2
    - ipython-pygments-lexers==1.1.1
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.4.2
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - langchain==0.3.20
    - langchain-community==0.3.19
    - langchain-core==0.3.43
    - langchain-groq==0.2.5
    - langchain-text-splitters==0.3.6
    - langgraph==0.3.5
    - langgraph-checkpoint==2.0.18
    - langgraph-prebuilt==0.1.2
    - langgraph-sdk==0.1.55
    - langsmith==0.3.13
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - marshmallow==3.26.1
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multidict==6.1.0
    - mypy-extensions==1.0.0
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - numpy==2.2.3
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - openpyxl==3.1.5
    - orjson==3.10.15
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.1.0
    - pinecone==6.0.1
    - pinecone-plugin-interface==0.0.7
    - platformdirs==4.3.6
    - prompt-toolkit==3.0.50
    - propcache==0.3.0
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pydantic-settings==2.8.1
    - pydub==0.25.1
    - pygments==2.19.1
    - pymupdf==1.25.3
    - pymupdf4llm==0.0.17
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-multipart==0.0.20
    - pytz==2025.1
    - pyyaml==6.0.2
    - pyzmq==26.2.1
    - regex==2024.11.6
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - rich==13.9.4
    - ruff==0.9.10
    - safehttpx==0.1.6
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - semantic-version==2.10.0
    - sentence-transformers==3.4.1
    - shellingham==1.5.4
    - six==1.17.0
    - sniffio==1.3.1
    - sqlalchemy==2.0.38
    - stack-data==0.6.3
    - starlette==0.46.1
    - sympy==1.13.1
    - tenacity==9.0.0
    - threadpoolctl==3.5.0
    - tiktoken==0.9.0
    - tokenizers==0.21.0
    - tomlkit==0.13.2
    - torch==2.6.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.49.0
    - triton==3.2.0
    - typer==0.15.2
    - typing-extensions==4.12.2
    - typing-inspect==0.9.0
    - tzdata==2025.1
    - urllib3==2.3.0
    - uvicorn==0.34.0
    - wcwidth==0.2.13
    - websockets==15.0.1
    - yarl==1.18.3
    - zstandard==0.23.0
